name: flutter_carrotmarket
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  geolocator: ^7.7.1 # GPS

  http: ^0.13.4
  http_parser: ^4.0.1
  stomp_dart_client: ^0.4.4 # WebSocket STOMP

  kakao_flutter_sdk: ^1.1.1

  image_picker: ^0.8.5+3
  
  riverpod: ^1.0.3 # State management
  hooks_riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3

  google_fonts: ^2.3.3

  font_awesome_flutter: ^10.1.0
  
  intl: ^0.17.0

  jiffy: ^5.0.0 # DateUtil

  flutter_svg: ^1.0.3 # SVG

  lottie: ^1.3.0 # Lottie

  shimmer: ^2.0.0 # Shimmer

  pull_to_refresh: ^2.0.0



  freezed_annotation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable:
  build_runner:
  freezed: ^2.0.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/lottie/
    - assets/png/

  fonts:
    - family: SEBANG_Gothic_Bold
      fonts:
        - asset: fonts/SEBANG_Gothic_Bold.ttf